// ---------------------------------------------------------------------------
// This project is a self-taught exercise. For more examples of various coding
// projects, please see my GitHub portfolio at https://github.com/JayMassey98.
// ---------------------------------------------------------------------------

// ----------------------------------------------------------------
// WARNING: This is an autogenerated file, do not edit this at all!
// Any changes that are made will be lost when this is regenerated.
// ----------------------------------------------------------------

// ---------------------------------------------------------------------
// TIMESTAMP: This file was last autogenerated on <month> <day>, <year>.
// ---------------------------------------------------------------------

#include current_top_50_songs.h

const char current_top_50_songs[50][STRING_LENGTH_MAX + 1] =
{
    Clarity Mac Miller,
    Crowd Control - 3 Are Legend Remix Dimitri Vegas & Like Mike W&W 3 Are Legend,
    Put It On Mac Miller,
    Watching Movies - Live Mac Miller,
    REMember - Live Mac Miller,
    Live The Night W&W Hardwell Lil Jon,
    Objects in the Mirror - Live Mac Miller,
    Party Till We Die (feat. Andrew W.K.) MAKJ Timmy Trumpet Andrew W.K.,
    Thoughts from a Balcony Mac Miller,
    Too Bad I Have To Destroy You Now Kid Cudi,
    Solo Dolo Pt. III Kid Cudi,
    Fight the Feeling Mac Miller Kendrick Lamar Iman Omari,
    Come Back to Earth Mac Miller,
    The Mourning After Mac Miller,
    On And On Mac Miller,
    One Last Thing Mac Miller,
    Feel The Love KIDS SEE GHOSTS Pusha T,
    Colors and Shapes Mac Miller,
    Live Free Mac Miller,
    English Lane Mac Miller,
    S.D.S. - Live Mac Miller,
    The Question - Live Mac Miller,
    Kickin' Incredibly Dope Shit (Intro) Mac Miller,
    Blue Slide Park Mac Miller,
    The Void Kid Cudi,
    United In Grief Kendrick Lamar,
    S.D.S. Mac Miller,
    Life Ain't Easy Mac Miller,
    1 Threw 8 Mac Miller,
    Repeat After Me Dimitri Vegas & Like Mike Armin van Buuren W&W,
    Grand Finale Mac Miller,
    Scream Tiësto John Christian,
    Rose Golden Kid Cudi WILLOW,
    Reborn KIDS SEE GHOSTS,
    Cudi Montage KIDS SEE GHOSTS,
    Sad People Kid Cudi,
    By Design Kid Cudi Andre Benjamin,
    Aliens Fighting Robots Mac Miller Sir Michael Rocks,
    The Question Mac Miller Lil Wayne,
    Vitamins Mac Miller,
    Blah Blah Blah Armin van Buuren,
    Diamonds & Gold (Commentary) Mac Miller,
    Frick Park Market Mac Miller,
    Hole In My Pocket Mac Miller,
    So It Goes Mac Miller,
    English Lane Mac Miller,
    We Don't Care Kanye West,
    Get Em Up Mac Miller,
    Frequency Kid Cudi,
    Perfecto Mac Miller
};